Organize repo
zlaraib/Test_rep pull request #19
Opened 2024-10-13 03:10 UTC by zlaraib

pushed changes (for particle's new position configuration), and changed neutrino number accordingly (in initializations file). Added swap stuff still experimenting (commented part in gates_function file). And other minor changes in test script for different parameters. This is not part of the reorganization, I am just cleaning up the current progress to delete this branch and start new progress in another one from here. Sorry for the overlook.

2024-11-19 11:06 UTC, srichers requested changes
Looks mostly good. Sorry for being so slow at reviewing - this really should happen in the same week you put up the PR. I don't remember which aspects you postponed to the next PR - just let me know if any of my requests are addressed there and I'll approve.

2024-11-19 11:06 UTC, srichers commented on Initializations/initial_cond.jl
> +    # N_νₑ  = n_νₑ * V
Should we just delete the old code we aren't using anymore?

2024-11-19 11:06 UTC, srichers commented on Initializations/initial_cond.jl
> +# # generate x_array such that the first particle is at position L/(2*N_sites) while subsequent particles are at a position incremental by L/N_sites. # grid style
delete unused code?

2024-11-19 11:06 UTC, srichers commented on Initializations/initial_cond.jl
> +function generate_antimu_x_array(N_sites_eachflavor, L)
It looks like these functions do the same thing - should they be combined into a single function?

2024-11-19 11:06 UTC, srichers commented on src/evolution.jl
> +        if shape_name!=="none" #specfic to the inhomogenous case Test4
I think we talked about this, but the shape name shouldn't be used to determine what the test case is. I don't think it would be problematic to compute sz at each step no matter what, and just calculate the mean in post-processing for the test cases where you need that.

2024-11-19 11:06 UTC, srichers commented on src/evolution.jl
> +        if shape_name!=="none" #specfic to the inhomogenous case Test4
Then this could be simplified and not have an if/else switch here.

2024-11-19 11:06 UTC, srichers commented on src/gates_function.jl
> +
remove unused code?

2024-11-19 11:06 UTC, srichers commented on src/gates_function.jl
> +# function create_gates(s,ψ, N, B, N_sites, Δx, Δm², p, x, Δp, theta_nu, shape_name,L, τ, energy_sign, periodic)
remove unused code?

2024-11-19 11:06 UTC, srichers commented on src/perturb.jl
> +function evolve_perturbation(s,k, τ_pert, B_pert, α, x, L, N_sites, ψ, cutoff, maxdim, energy_sign,ttotal)
There shouldn't be a separate evolve function, I think. You should apply the perturbation in a single step. w and tau shouldn't be separate arguments - you should pass a single parameter called "amplitude", which is equivalent to (w*tau)

2024-11-19 11:06 UTC, srichers commented on tests/Inhomo_FFI_MB.jl
> +# Δx = L/N_sites # length of the box of interacting neutrinos at a site in cm  #variable
remove unused code?

2024-11-19 11:06 UTC, srichers commented on tests/Inhomo_FFI_MB.jl
> +# Δp = L
remove unused code?

2024-11-19 11:06 UTC, srichers commented on tests/Inhomo_FFI_MB.jl
> +y = generate_x_array(N_sites_eachflavor, L)
Why do y and z also have an array of values? They should both be constant, right?

2024-11-19 11:06 UTC, srichers commented on tests/Inhomo_FFI_MB.jl
> +# @assert abs((Im_Ω - analytic_growth_rate)/  analytic_growth_rate) < tolerance
Should this be uncommented?

2024-11-19 11:06 UTC, srichers commented on tests/Inhomogenous_FFI_MF_Richers.jl
> +# Δx = L/N_sites # length of the box of interacting neutrinos at a site in cm  #variable
remove unused code?

2024-11-19 11:06 UTC, srichers commented on tests/Inhomogenous_FFI_MF_Richers.jl
> +# Δp = L
remove unused code?

2024-11-19 11:06 UTC, srichers commented on tests/Inhomogenous_FFI_MF_Richers.jl
> +y = generate_x_array(N_sites_eachflavor, L)
do y and z need arrays?

2024-11-19 11:06 UTC, srichers commented on tests/Inhomogenous_FFI_MF_Richers.jl
> +# @assert abs((Im_Ω - analytic_growth_rate)/  analytic_growth_rate) < tolerance
uncomment assert?

2024-12-04 07:49 UTC, zlaraib commented on src/evolution.jl
> +        if shape_name!=="none" #specfic to the inhomogenous case Test4
created issue- will address all if else statements in src files in a separate branch

2024-12-04 08:14 UTC, merged