Reorg evol
zlaraib/Test_rep pull request #33
Opened 2024-12-29 18:19 UTC by zlaraib

Addressed the issues started

2025-01-02 16:27 UTC, srichers requested changes
I didn't look over the test scripts - just the core code. There are a couple of things I think we can hack out together quickly - chat with me when you have time.

2025-01-02 16:27 UTC, srichers commented on Utilities/save_datafiles.jl
> +        fname1 = joinpath(datadir, "t_<Sz>.dat")
It looks like this writes the entire t-vs-quantity array at every output timestep. Do you not want to just append each file with new data?

2025-01-02 16:27 UTC, srichers commented on Utilities/save_datafiles.jl
> +        fname1 = joinpath(datadir, "t_<Sz>.dat")
Also, why is there checkpoint data both here and in the checkpoint hdf5 function?

2025-01-02 16:27 UTC, srichers commented on src/evolution.jl
> +            checkpoint_files = sort(checkpoint_files)
Should the checkpoint file string just be an optional argument instead of searching for them? This would give you the additional flexibility to restart from any file, and not tie you to only restarting from the latest checkpoint in your current directory.

2025-01-02 16:27 UTC, srichers commented on src/evolution.jl
> +            checkpoint_files = sort(checkpoint_files)
Perhaps that's a comment for the "manual" section below. You can just pass the filename instead of the iteration.

2025-01-02 16:27 UTC, srichers commented on src/evolution.jl
> +            checkpoint_files = sort(checkpoint_files)
Also, both functions share the actual "recover_checkpoint_hdf5" function, so that (and later) lines can be removed from the recover_type if statements.

2025-01-02 16:27 UTC, srichers commented on src/evolution.jl
> +    is_first_iteration = true  # Flag to mark the first iteration of the loop
Can this not be replaced with a line before the loop? You can just set:
t_recover = t_initial
and delete the if statement and the is_first_iteration variable

2025-01-02 16:27 UTC, srichers commented on src/evolution.jl
> +        sy_tot = expect(complex(ψ), "Sy")
Why is psi wrapped in "complex" only for one of the expectation values?

2025-01-02 16:27 UTC, srichers commented on src/evolution.jl
> +        prob_surv_tot = 0.5 * (1 .- 2 .* sz_tot)
This definition of survival probability only applies to specific initial conditions. I would remove these lines and relegate survival probability to post-processing. I think rho_ee would probably be a good diagnostic to print instead.

2025-01-02 16:27 UTC, srichers commented on src/evolution.jl
> +        store_data(do_recover, datadir, iteration, checkpoint_every, t_array, Sz_array, Sy_array, Sx_array, prob_surv_array,x_values, pₓ_values, ρₑₑ_array,ρ_μμ_array, ρₑμ_array)
I think this should be done inside of the time loop as well, via appending to files. Otherwise, if a simulation terminates, you only have the checkpoint data and not the data that you store here.

2025-01-02 16:27 UTC, srichers commented on src/evolution.jl
> +    return Sz_array, Sy_array, Sx_array, prob_surv_array, x_values, pₓ_values, ρₑₑ_array, ρ_μμ_array, ρₑμ_array, t_array, t_recover
Does evol need to return anything?

2025-01-02 16:27 UTC, srichers commented on src/gates_function.jl
> +include("geometric_func.jl")
I think these should be included only once.

2025-01-02 16:27 UTC, srichers commented on src/gates_function.jl
> +            # add Vacuum Oscillation Hamiltonian
remove commented code?

2025-01-02 16:27 UTC, srichers commented on src/gates_function.jl
> +            if theta_nu == 0 ||  theta_nu == π/4 || theta_nu == π/2
These if statments detect which test is being run in an esoteric way. I think they should be removed.

2025-01-02 16:27 UTC, srichers commented on src/perturb.jl
>      ω_pert = asin.([α * sin(k*x[i])* energy_sign[i] for i in 1:N_sites])
I think the description of the input parameters needs to be adjusted based on the arguments to the function.

2025-01-02 16:27 UTC, srichers commented on src/perturb.jl
> +            hj= (
Why is this looping over sites twice and using a two-body operator? Shouldn't we just loop over sites once and apply the perturbation to each site separately? Does this mean that the perturbation will be larger if the number of sites is larger (since it gets applied multiple times)?

2025-01-02 16:27 UTC, srichers commented on src/perturb.jl
> +     for t in 0.0:τ_pert:ttotal  #perhaps not perturn till the end? stop somewhere in the mid
The perturbaton only needs to be applied once - I think we need to discuss this again

2025-01-02 18:43 UTC, zlaraib commented
Thanks! Can I come to your office tomorrow sometime to discuss these
changes? I’m at ORNL today.

On Thu, Jan 2, 2025 at 11:27 Sherwood Richers ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> I didn't look over the test scripts - just the core code. There are a
> couple of things I think we can hack out together quickly - chat with me
> when you have time.
> ------------------------------
>
> In Utilities/save_datafiles.jl
> <https://github.com/zlaraib/CCNO/pull/33#discussion_r1901023269>:
>
> > @@ -0,0 +1,132 @@
> +
> +
> +function store_data(do_recover, datadir, iteration, checkpoint_every, t_array, Sz_array, Sy_array, Sx_array, prob_surv_array,x_values, pₓ_values, ρₑₑ_array,ρ_μμ_array, ρₑμ_array)
> +
> +    if !do_recover
> +        save_data = isdir(datadir) || mkpath(datadir)
> +        # Writing data to files with corresponding headers
> +        # 1. Sz arrays
> +        fname1 = joinpath(datadir, "t_<Sz>.dat")
>
> It looks like this writes the entire t-vs-quantity array at every output
> timestep. Do you not want to just append each file with new data?
> ------------------------------
>
> In src/evolution.jl
> <https://github.com/zlaraib/CCNO/pull/33#discussion_r1901029203>:
>
> > -    t_array = [] # to store t values
> -    prob_surv_array = Float64[]   # to store survival probability values
> +function evolve(s, τ, N, B, L, N_sites, Δx, Δm², p, x, Δp, theta_nu, ψ, shape_name, energy_sign, cutoff, maxdim, datadir, t1, t2, ttotal, chkptdir, checkpoint_every, do_recover, recover_type, recover_iteration, save_data::Bool, periodic=true)
> +
> +    t_initial = 0.0
> +    iteration = 0
> +    t_recover = 0.0  # Variable to store the initial recovery time
> +
> +    if do_recover
> +
> +        if recover_type == "auto"
> +            println("auto recovery: recovering from last iteration")
> +            recover_iteration = -1
> +            checkpoint_files = readdir(chkptdir)
> +            checkpoint_files = filter(f -> endswith(f, ".h5"), checkpoint_files)
> +            checkpoint_files = sort(checkpoint_files)
>
> Should the checkpoint file string just be an optional argument instead of
> searching for them? This would give you the additional flexibility to
> restart from any file, and not tie you to only restarting from the latest
> checkpoint in your current directory.
> ------------------------------
>
> In src/evolution.jl
> <https://github.com/zlaraib/CCNO/pull/33#discussion_r1901032187>:
>
> >      # extract output of p_hat and p_mod for the p vector defined above for all sites.
>      p_mod, p̂ = momentum(p,N_sites)
>      p̂ₓ= [sub_array[1] for sub_array in p̂]
>
> +    # Main evolution loop
> +    is_first_iteration = true  # Flag to mark the first iteration of the loop
>
> Can this not be replaced with a line before the loop? You can just set:
> t_recover = t_initial
> and delete the if statement and the is_first_iteration variable
> ------------------------------
>
> In src/evolution.jl
> <https://github.com/zlaraib/CCNO/pull/33#discussion_r1901032737>:
>
> >
> -        # add an element prob_surv to the end of  prob_surv_array
> -        push!(prob_surv_array, prob_surv)
> +        # compute expectation value of sy and sx (inbuilt operator in ITensors library) at all sites on the chain
> +        sy_tot = expect(complex(ψ), "Sy")
>
> Why is psi wrapped in "complex" only for one of the expectation values?
> ------------------------------
>
> In src/evolution.jl
> <https://github.com/zlaraib/CCNO/pull/33#discussion_r1901034663>:
>
> >
> +        #survival probability for all sites (neutrino) to be found in its initial flavor state
> +        prob_surv_tot = 0.5 * (1 .- 2 .* sz_tot)
>
> This definition of survival probability only applies to specific initial
> conditions. I would remove these lines and relegate survival probability to
> post-processing. I think rho_ee would probably be a good diagnostic to
> print instead.
> ------------------------------
>
> In src/evolution.jl
> <https://github.com/zlaraib/CCNO/pull/33#discussion_r1901036746>:
>
> >      end
> -
> -    return Sz_array, Sy_array, Sx_array, prob_surv_array, x_values, pₓ_values, ρₑₑ_array, ρ_μμ_array, ρₑμ_array, Im_Ω
> +    t_array = t_initial:τ:ttotal
> +
> +    if save_data
> +        store_data(do_recover, datadir, iteration, checkpoint_every, t_array, Sz_array, Sy_array, Sx_array, prob_surv_array,x_values, pₓ_values, ρₑₑ_array,ρ_μμ_array, ρₑμ_array)
>
> I think this should be done inside of the time loop as well, via appending
> to files. Otherwise, if a simulation terminates, you only have the
> checkpoint data and not the data that you store here.
> ------------------------------
>
> In src/evolution.jl
> <https://github.com/zlaraib/CCNO/pull/33#discussion_r1901037040>:
>
> >      end
> -
> -    return Sz_array, Sy_array, Sx_array, prob_surv_array, x_values, pₓ_values, ρₑₑ_array, ρ_μμ_array, ρₑμ_array, Im_Ω
> +    t_array = t_initial:τ:ttotal
> +
> +    if save_data
> +        store_data(do_recover, datadir, iteration, checkpoint_every, t_array, Sz_array, Sy_array, Sx_array, prob_surv_array,x_values, pₓ_values, ρₑₑ_array,ρ_μμ_array, ρₑμ_array)
> +    end
> +
> +    return Sz_array, Sy_array, Sx_array, prob_surv_array, x_values, pₓ_values, ρₑₑ_array, ρ_μμ_array, ρₑμ_array, t_array, t_recover
>
> Does evol need to return anything?
> ------------------------------
>
> In src/gates_function.jl
> <https://github.com/zlaraib/CCNO/pull/33#discussion_r1901037427>:
>
> >  include("constants.jl")
>  include("geometric_func.jl")
>  include("shape_func.jl")
>  include("momentum.jl")
>
> +include("geometric_func.jl")
>
> I think these should be included only once.
> ------------------------------
>
> In src/gates_function.jl
> <https://github.com/zlaraib/CCNO/pull/33#discussion_r1901037868>:
>
> > @@ -94,15 +116,30 @@ function create_gates(s, ψ, N, B, N_sites, Δx, Δm², p, x, Δp, theta_nu, sha
>                  # op("S-", s_i) * op("S+", s_j))
>              # end
>
> +            # add Vacuum Oscillation Hamiltonian
>
> remove commented code?
> ------------------------------
>
> In src/gates_function.jl
> <https://github.com/zlaraib/CCNO/pull/33#discussion_r1901038745>:
>
> > @@ -118,6 +155,20 @@ function create_gates(s, ψ, N, B, N_sites, Δx, Δm², p, x, Δp, theta_nu, sha
>              # println((Δm²))/(2 *hbar * p_mod[1])
>              # @assert imag(hj) == ((Δm²))/(2 *hbar * p_mod[1])
>              # println("Gj= ",Gj)            # has_fermion_string(hj) = true
> +            if theta_nu == 0 ||  theta_nu == π/4 || theta_nu == π/2
>
> These if statments detect which test is being run in an esoteric way. I
> think they should be removed.
> ------------------------------
>
> In src/perturb.jl
> <https://github.com/zlaraib/CCNO/pull/33#discussion_r1901042328>:
>
> > @@ -29,8 +29,6 @@ function create_perturbation_gates(s, k, B_pert, α, x, L, N_sites, energy_sign,
>      gates = ITensor[]
>
>      # define an array of oscillation frequencies (units of ergs) of perturbation
> -    # ω_pert = [10^(-28)* energy_sign[i] for i in 1:N_sites]
> -    # ω_pert = fill(2π*(10^(-26)), N_sites)
>      ω_pert = asin.([α * sin(k*x[i])* energy_sign[i] for i in 1:N_sites])
>
> I think the description of the input parameters needs to be adjusted based
> on the arguments to the function.
> ------------------------------
>
> In src/perturb.jl
> <https://github.com/zlaraib/CCNO/pull/33#discussion_r1901043745>:
>
> >              # total Hamiltonian of the system is a sum of local terms hj, where hj acts on sites i and j which are paired for gates to latch onto.
>              # op function returns these operators as ITensors and we tensor product and add them together to compute the operator hj.
>
>              # add perturbation via one-body oscillation term to the Hamiltonian
> -            # hj = (1/(N_sites-1))* (
> -            # ((ω_pert[i] * B[1] * op("Sx", s_i)* op("Id", s_j))  + (ω_pert[j] * B[1] * op("Sx", s_j) * op("Id", s_i))) +
> -            # ((ω [...]

2025-01-02 18:44 UTC, zlaraib commented
Thanks! Can I come to your office tomorrow sometime to discuss these
changes? I’m at ORNL today.


On Thu, Jan 2, 2025 at 11:27 Sherwood Richers ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> I didn't look over the test scripts - just the core code. There are a
> couple of things I think we can hack out together quickly - chat with me
> when you have time.
> ------------------------------
>
> In Utilities/save_datafiles.jl
> <https://github.com/zlaraib/CCNO/pull/33#discussion_r1901023269>:
>
> > @@ -0,0 +1,132 @@
> +
> +
> +function store_data(do_recover, datadir, iteration, checkpoint_every, t_array, Sz_array, Sy_array, Sx_array, prob_surv_array,x_values, pₓ_values, ρₑₑ_array,ρ_μμ_array, ρₑμ_array)
> +
> +    if !do_recover
> +        save_data = isdir(datadir) || mkpath(datadir)
> +        # Writing data to files with corresponding headers
> +        # 1. Sz arrays
> +        fname1 = joinpath(datadir, "t_<Sz>.dat")
>
> It looks like this writes the entire t-vs-quantity array at every output
> timestep. Do you not want to just append each file with new data?
> ------------------------------
>
> In src/evolution.jl
> <https://github.com/zlaraib/CCNO/pull/33#discussion_r1901029203>:
>
> > -    t_array = [] # to store t values
> -    prob_surv_array = Float64[]   # to store survival probability values
> +function evolve(s, τ, N, B, L, N_sites, Δx, Δm², p, x, Δp, theta_nu, ψ, shape_name, energy_sign, cutoff, maxdim, datadir, t1, t2, ttotal, chkptdir, checkpoint_every, do_recover, recover_type, recover_iteration, save_data::Bool, periodic=true)
> +
> +    t_initial = 0.0
> +    iteration = 0
> +    t_recover = 0.0  # Variable to store the initial recovery time
> +
> +    if do_recover
> +
> +        if recover_type == "auto"
> +            println("auto recovery: recovering from last iteration")
> +            recover_iteration = -1
> +            checkpoint_files = readdir(chkptdir)
> +            checkpoint_files = filter(f -> endswith(f, ".h5"), checkpoint_files)
> +            checkpoint_files = sort(checkpoint_files)
>
> Should the checkpoint file string just be an optional argument instead of
> searching for them? This would give you the additional flexibility to
> restart from any file, and not tie you to only restarting from the latest
> checkpoint in your current directory.
> ------------------------------
>
> In src/evolution.jl
> <https://github.com/zlaraib/CCNO/pull/33#discussion_r1901032187>:
>
> >      # extract output of p_hat and p_mod for the p vector defined above for all sites.
>      p_mod, p̂ = momentum(p,N_sites)
>      p̂ₓ= [sub_array[1] for sub_array in p̂]
>
> +    # Main evolution loop
> +    is_first_iteration = true  # Flag to mark the first iteration of the loop
>
> Can this not be replaced with a line before the loop? You can just set:
> t_recover = t_initial
> and delete the if statement and the is_first_iteration variable
> ------------------------------
>
> In src/evolution.jl
> <https://github.com/zlaraib/CCNO/pull/33#discussion_r1901032737>:
>
> >
> -        # add an element prob_surv to the end of  prob_surv_array
> -        push!(prob_surv_array, prob_surv)
> +        # compute expectation value of sy and sx (inbuilt operator in ITensors library) at all sites on the chain
> +        sy_tot = expect(complex(ψ), "Sy")
>
> Why is psi wrapped in "complex" only for one of the expectation values?
> ------------------------------
>
> In src/evolution.jl
> <https://github.com/zlaraib/CCNO/pull/33#discussion_r1901034663>:
>
> >
> +        #survival probability for all sites (neutrino) to be found in its initial flavor state
> +        prob_surv_tot = 0.5 * (1 .- 2 .* sz_tot)
>
> This definition of survival probability only applies to specific initial
> conditions. I would remove these lines and relegate survival probability to
> post-processing. I think rho_ee would probably be a good diagnostic to
> print instead.
> ------------------------------
>
> In src/evolution.jl
> <https://github.com/zlaraib/CCNO/pull/33#discussion_r1901036746>:
>
> >      end
> -
> -    return Sz_array, Sy_array, Sx_array, prob_surv_array, x_values, pₓ_values, ρₑₑ_array, ρ_μμ_array, ρₑμ_array, Im_Ω
> +    t_array = t_initial:τ:ttotal
> +
> +    if save_data
> +        store_data(do_recover, datadir, iteration, checkpoint_every, t_array, Sz_array, Sy_array, Sx_array, prob_surv_array,x_values, pₓ_values, ρₑₑ_array,ρ_μμ_array, ρₑμ_array)
>
> I think this should be done inside of the time loop as well, via appending
> to files. Otherwise, if a simulation terminates, you only have the
> checkpoint data and not the data that you store here.
> ------------------------------
>
> In src/evolution.jl
> <https://github.com/zlaraib/CCNO/pull/33#discussion_r1901037040>:
>
> >      end
> -
> -    return Sz_array, Sy_array, Sx_array, prob_surv_array, x_values, pₓ_values, ρₑₑ_array, ρ_μμ_array, ρₑμ_array, Im_Ω
> +    t_array = t_initial:τ:ttotal
> +
> +    if save_data
> +        store_data(do_recover, datadir, iteration, checkpoint_every, t_array, Sz_array, Sy_array, Sx_array, prob_surv_array,x_values, pₓ_values, ρₑₑ_array,ρ_μμ_array, ρₑμ_array)
> +    end
> +
> +    return Sz_array, Sy_array, Sx_array, prob_surv_array, x_values, pₓ_values, ρₑₑ_array, ρ_μμ_array, ρₑμ_array, t_array, t_recover
>
> Does evol need to return anything?
> ------------------------------
>
> In src/gates_function.jl
> <https://github.com/zlaraib/CCNO/pull/33#discussion_r1901037427>:
>
> >  include("constants.jl")
>  include("geometric_func.jl")
>  include("shape_func.jl")
>  include("momentum.jl")
>
> +include("geometric_func.jl")
>
> I think these should be included only once.
> ------------------------------
>
> In src/gates_function.jl
> <https://github.com/zlaraib/CCNO/pull/33#discussion_r1901037868>:
>
> > @@ -94,15 +116,30 @@ function create_gates(s, ψ, N, B, N_sites, Δx, Δm², p, x, Δp, theta_nu, sha
>                  # op("S-", s_i) * op("S+", s_j))
>              # end
>
> +            # add Vacuum Oscillation Hamiltonian
>
> remove commented code?
> ------------------------------
>
> In src/gates_function.jl
> <https://github.com/zlaraib/CCNO/pull/33#discussion_r1901038745>:
>
> > @@ -118,6 +155,20 @@ function create_gates(s, ψ, N, B, N_sites, Δx, Δm², p, x, Δp, theta_nu, sha
>              # println((Δm²))/(2 *hbar * p_mod[1])
>              # @assert imag(hj) == ((Δm²))/(2 *hbar * p_mod[1])
>              # println("Gj= ",Gj)            # has_fermion_string(hj) = true
> +            if theta_nu == 0 ||  theta_nu == π/4 || theta_nu == π/2
>
> These if statments detect which test is being run in an esoteric way. I
> think they should be removed.
> ------------------------------
>
> In src/perturb.jl
> <https://github.com/zlaraib/CCNO/pull/33#discussion_r1901042328>:
>
> > @@ -29,8 +29,6 @@ function create_perturbation_gates(s, k, B_pert, α, x, L, N_sites, energy_sign,
>      gates = ITensor[]
>
>      # define an array of oscillation frequencies (units of ergs) of perturbation
> -    # ω_pert = [10^(-28)* energy_sign[i] for i in 1:N_sites]
> -    # ω_pert = fill(2π*(10^(-26)), N_sites)
>      ω_pert = asin.([α * sin(k*x[i])* energy_sign[i] for i in 1:N_sites])
>
> I think the description of the input parameters needs to be adjusted based
> on the arguments to the function.
> ------------------------------
>
> In src/perturb.jl
> <https://github.com/zlaraib/CCNO/pull/33#discussion_r1901043745>:
>
> >              # total Hamiltonian of the system is a sum of local terms hj, where hj acts on sites i and j which are paired for gates to latch onto.
>              # op function returns these operators as ITensors and we tensor product and add them together to compute the operator hj.
>
>              # add perturbation via one-body oscillation term to the Hamiltonian
> -            # hj = (1/(N_sites-1))* (
> -            # ((ω_pert[i] * B[1] * op("Sx", s_i)* op("Id", s_j))  + (ω_pert[j] * B[1] * op("Sx", s_j) * op("Id", s_i))) +
> -            # (( [...]

2025-01-23 20:16 UTC, srichers approved these changes
The remaining comments have been listed as issues.

2025-01-24 14:42 UTC, merged